id: AD95E5395
base_file: fC50A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:04:45.256407
  last_modified_at: 2022-05-30 22:04:45.256413
